name: Deploy to Cloudflare

on:
  push:
    branches:
      - main # 或者你的部署分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 或者你偏好的 Node.js 版本

      - name: Install dependencies
        run: npm install

      # 假设 'aia_db' 是你在 wrangler.toml 中定义的 D1 数据库名称
      # 并且你的迁移文件位于默认的 'migrations' 文件夹中
      - name: Apply D1 Migrations
        run: npx wrangler d1 migrations apply aia_db --local=false # 对生产环境部署使用 --local=false
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy Worker
        run: npx wrangler deploy --minify
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 如果需要，将其他环境变量也添加为 secrets
          API_PASSWORD: ${{ secrets.API_PASSWORD }}